require('dotenv').config()
const express=require('express')
const mongoose=require('mongoose')
const cors=require('cors')
const authroutes=require('./routes/authroutes.js')
const submissionroutes=require('./routes/submissionroutes.js')
const judgmentroutes=require('./routes/judgmentroutes.js')
const startcron=require('./unlockjob.js')
const app=express()
app.use(cors())
app.use(express.json())
app.use('/api/auth',authroutes)
app.use('/api/submissions',submissionroutes)
app.use('/api/judgments',judgmentroutes)
const dburi=process.env.MONGOURI
mongoose.connect(dburi)
startcron()
const portnum=process.env.PORT||5000
app.listen(portnum,()=>console.log('Server running on port '+portnum))