require('dotenv').config()
const express=require('express')
const mongoose=require('mongoose')
const cors=require('cors')
const path=require('path')
const authroutes=require('./routes/authroutes.js')
const submissionroutes=require('./routes/submissionroutes.js')
const judgementroutes=require('./routes/judgementroutes.js')
const userroutes=require('./routes/userroutes.js')
const startcron=require('./unlockjob.js')
const app=express()
app.use(cors())
app.use(express.json())
app.use('/api/auth',authroutes)
app.use('/api/submissions',submissionroutes)
app.use('/api/judgments',judgementroutes)
app.use('/api/users',userroutes)
const dburi=process.env.MONGOURI
mongoose.connect(dburi).then(() => {
	console.log('Connected to MongoDB')
}).catch((error) => {
	console.error('MongoDB connection error:', error)
})
startcron()
app.use(express.static(path.join(__dirname,'../client/dist')))
app.get(/(.*)/,(req,res)=>{
	res.sendFile(path.join(__dirname,'../client/dist/index.html'))
})
const portnum=process.env.PORT||5000
app.listen(portnum,()=>console.log('Server running on port '+portnum))